### PR TITLE
Migrate on dio5

### PR DESCRIPTION
**Pull request by dkrutskikh**

### CODE REVIEW

**Comment by dkrutskikh** [comment]
@matthewelwell please take a look

**Comment by Dan-Crane** [comment]
any updates?

**Comment by matthewelwell** [comment]
Hi @dkrutskikh, @Dan-Crane, we will get to this shortly. Please bear with us. Thanks!

**Comment by matthewelwell** [comment]
Hi @dkrutskikh, I noticed that the workflows were only being triggered on merges (and had been failing) so I've updated that in the main branch now - could you please rebase / merge our main branch branch into this PR so that we can verify that the workflows pass?

**Comment by dkrutskikh** [comment]
@matthewelwell done

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
